SELECT 
    C.CUSTOMERID AS CUSTOMER_ID,
    C.CUSTOMERNAME AS CUSTOMER_NAME,
    C.SEGMENT AS CUSTOMER_SEGMENT,
    C.COUNTRY AS CUSTOMER_COUNTRY,
    C.STATE AS CUSTOMER_STATE,
    O.ORDER_ID,
    O.ORDER_DATE,
    O.SHIP_DATE,
    O.SHIP_MODE,
    P.CATEGORY AS PRODUCT_CATEGORY,
    P.SUBCATEGORY AS PRODUCT_SUBCATEGORY,
    P.PRODUCTNAME AS PRODUCT_NAME,
    (O.ORDER_SELLING_PRICE - O.ORDER_COST_PRICE) AS PROFIT
FROM  {{ source('RAW_DATA','RAW_ORDERS')}} O
JOIN {{ source('RAW_DATA','RAW_CUSTOMERS')}} C
    ON O.CUSTOMER_ID = C.CUSTOMERID
JOIN {{ source('RAW_DATA','RAW_PRODUCTS')}} P
    ON O.PRODUCT_ID = P.PRODUCTID
WHERE 
    DATEDIFF(DAY, O.ORDER_DATE, O.SHIP_DATE) <= 10
