name: 'DBT_Materializations'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


models:
  DBT_Materializations:
    +database: TRANSFORM_DB
    +materialized: table
    +pre-hook:
      - "{{ log_model_start(this) }}"
    +post-hook:
      - "{{ log_model_end(this, success=true) }}"

on-run-end:
  - "{{ log_failed_models(results) }}"
