version: 2

sources:
  - name: RAW_DATA
    description: Snowflake details 
    database: TRANSFORM_DB  
    schema: RAW_SCH 
    tables:
      - name: RAW_ORDERS
      - name: RAW_CUSTOMERS
      - name: RAW_PRODUCTS
      - name: EMPLOYEES
      - name: SIMPLE_DATA_NULL_TBL
      - name: EMAIL_TEST_TBL

